# Generated by Django 3.0.3 on 2020-03-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sma', '0005_session_schedule_session_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
